version: '3.8'
services:
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/graphql
    depends_on:
      - backend

  backend:
    build: ./apps/backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
